dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "kelkoo"
    token:
      secure: "6c199a8887e5909a63eb3d6ffcd70c1ca33d6757"

language: scala
jdk:
  - oraclejdk8
scala:
   - 2.12.4
cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
  - $HOME/.sbt
  - '$HOME/.sonar/cache'
script:
   - sbt ++$TRAVIS_SCALA_VERSION clean +testscript:
   - sonar-scanner
   
   
