sudo: required

language: scala

addons:
    sonarcloud:
        organization: kelkoo
        token:
            secure: 6c199a8887e5909a63eb3d6ffcd70c1ca33d6757
    apt:
        sources:
            - google-chrome
        packages:
            - google-chrome-stable
            - nodejs

node_js:
    - 8.12.0
jdk:
    - oraclejdk8
scala:
    - 2.12.7

cache:
    directories:
        - $HOME/.m2
        - $HOME/.ivy2
        - $HOME/.sbt
        - $HOME/.sonar/cache
        - $HOME/node_modules/
        - $HOME/frontend/node_modules
git:
    depth: false

before_script:
    - 'set -e'
    - 'cd frontend'
    - 'npm install -g @angular/cli'
    - 'export PATH=$(npm prefix -g)/bin:$PATH'
    - 'npm install'
    - 'export DISPLAY=:99.0'
    - 'sh -e /etc/init.d/xvfb start'

script:
    - 'ng lint --force=true'
    - 'ng test --watch=false --progress=false --code-coverage'
    - 'ng e2e'
    - 'ng build --no-progress --prod --deploy-url /assets/dist/'
    - 'cd ..'
    - 'sbt ++$TRAVIS_SCALA_VERSION clean coverage test dist'
    - sonar-scanner
