sudo: required

language: scala

addons:
    sonarcloud:
        organization: kelkoo
        token:
            secure: 6c199a8887e5909a63eb3d6ffcd70c1ca33d6757
    apt:
        sources:
            - google-chrome
        packages:
            - google-chrome-stable

services:
  - xvfb

jdk:
    - openjdk8
scala:
    - 2.12.8

cache:
    directories:
        - $HOME/.m2
        - $HOME/.ivy2
        - $HOME/.sbt
        - $HOME/node_modules/
        - $HOME/frontend/node_modules
git:
    depth: false

before_script:
    - 'nvm install --lts'
    - 'nvm use --lts'
    - 'set -e'
    - 'cd frontend'
    - 'npm install -g @angular/cli'
    - 'export PATH=$(npm prefix -g)/bin:$PATH'
    - 'npm install'

script:
    - './node_modules/tslint/bin/tslint -t json -o report.json --project . --force'
    - 'ng test --watch=false --progress=false --code-coverage'
    - 'ng e2e'
    - 'ng build --no-progress --prod --outputPath ../public/dist'
    - 'cd ..'
    - 'sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport scalastyle scapegoat dist'
    - sonar-scanner
