pool:
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - .azure-pipelines/frontend.yml
      - frontend/*

pr:
  branches:
    include:
      - '*'
  paths:
    include:
      - .azure-pipelines/frontend.yml
      - frontend/*

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - task: CacheBeta@0
    inputs:
      key: npm | $(Agent.OS) | frontend/package-lock.json
      path: frontend/node_modules
    displayName: Cache npm

  - script: |
      npm install -g @angular/cli
      npm install
      cd ./node_modules/protractor && npm i webdriver-manager@latest && cd ../..
      npm run pree2e
    workingDirectory: frontend
    displayName: 'npm install'

  - script: |
      export CI=true
      ./node_modules/tslint/bin/tslint -t json -o report.json --project . --force
      ng test --watch=false --progress=false --code-coverage
    workingDirectory: frontend
    displayName: 'npm test'

  - script:  |
      ng build --no-progress --prod --outputPath ../public/dist
    workingDirectory: frontend
    displayName: 'ng build --prod'

  - script: |
      sudo mkdir /opt/sonarscanner
      cd /opt/sonarscanner
      sudo wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.0.0.1744-linux.zip
      sudo unzip sonar-scanner-cli-4.0.0.1744-linux.zip
      sudo nano sonar-scanner-cli-4.0.0.1744-linux/conf/sonar-scanner.properties
      sudo chmod +x sonar-scanner-4.0.0.1744-linux/bin/sonar-scanner
      sudo ln -s /opt/sonarscanner/sonar-scanner-4.0.0.1744-linux/bin/sonar-scanner /usr/local/bin/sonar-scanner
    displayName: 'install sonar-scanner'

  - script: |
      if [ $(Build.Reason) = "PullRequest" ]; then SONAR_BRANCH="-Dsonar.pullrequest.key=$(System.PullRequest.PullRequestNumber) -Dsonar.pullrequest.branch=$(System.PullRequest.SourceBranch) -Dsonar.pullrequest.base=$(System.PullRequest.TargetBranch)"; else SONAR_BRANCH="-Dsonar.branch.name=$(Build.SourceBranchName)"; fi
      sh -x -c "sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=kelkoo -Dsonar.login=6c199a8887e5909a63eb3d6ffcd70c1ca33d6757 $SONAR_BRANCH"
    workingDirectory: frontend
    displayName: 'sonar-scanner'
