pool:
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    - frontend/*
    - .azure-pipelines/frontend.yml
pr: none

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    cd ./node_modules/protractor && npm i webdriver-manager@latest && cd ../..
    npm run pree2e
  displayName: 'npm install'
  workingDirectory: frontend

- script: |
    export CI=true
    ./node_modules/tslint/bin/tslint -t json -o report.json --project . --force
    ng test --watch=false --progress=false --code-coverage
    ng e2e
  displayName: 'npm test'
  workingDirectory: frontend

- script:  |
    ng build --no-progress --prod --outputPath ../public/dist
  displayName: 'ng build --prod'
  workingDirectory: frontend

- script: |
    sudo mkdir /opt/sonarscanner
    cd /opt/sonarscanner
    [ ! -d sonar-scanner-cli-4.0.0.1744-linux ] && sudo wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.0.0.1744-linux.zip
    [ ! -d sonar-scanner-cli-4.0.0.1744-linux ] && sudo unzip sonar-scanner-cli-4.0.0.1744-linux.zip
    [ ! -d sonar-scanner-cli-4.0.0.1744-linux ] && sudo rm sonar-scanner-cli-4.0.0.1744-linux.zip
    [ ! -d sonar-scanner-cli-4.0.0.1744-linux ] && sudo nano sonar-scanner-cli-4.0.0.1744-linux/conf/sonar-scanner.properties
    sudo chmod +x sonar-scanner-4.0.0.1744-linux/bin/sonar-scanner
    sudo ln -s /opt/sonarscanner/sonar-scanner-4.0.0.1744-linux/bin/sonar-scanner /usr/local/bin/sonar-scanner
  displayName: 'install sonar-scanner'

- script: |
    sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=kelkoo -Dsonar.login=6c199a8887e5909a63eb3d6ffcd70c1ca33d6757
  displayName: 'sonar-scanner'
  workingDirectory: frontend

- publish: $(System.DefaultWorkingDirectory)/frontend/node_modules
  artifact: node_modules

- publish: /opt/sonarscanner
  artifact: sonar-scanner
