
  pool:
    vmImage: 'ubuntu-latest'

  trigger:
    branches:
      include:
      - '*'
    paths:
      include:
      - frontend/*

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      apt-get autoremove google-chrome-stable
      cd frontend
      npm install -g @angular/cli
      npm install
    displayName: 'npm install'

  - script: |
      cd frontend
      export DISPLAY=:10
      sudo /usr/bin/Xvfb :10 -ac>>/tmp/Xvfb.out 2>&1 &
      ./node_modules/tslint/bin/tslint -t json -o report.json --project . --force
      ng test --watch=false --progress=false --code-coverage
      ng e2e
    displayName: 'npm test'

  - script:  |
      cd frontend
      ng build --no-progress --prod --outputPath ../public/dist
    displayName: 'ng build --prod'

  - script: |
      sudo mkdir /opt/sonarscanner
      cd /opt/sonarscanner
      sudo wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.0.0.1744-linux.zip
      sudo unzip sonar-scanner-cli-4.0.0.1744-linux.zip
      sudo rm sonar-scanner-cli-4.0.0.1744-linux.zip
      sudo nano sonar-scanner-cli-4.0.0.1744-linux/conf/sonar-scanner.properties
      sudo chmod +x sonar-scanner-4.0.0.1744-linux/bin/sonar-scanner
      sudo ln -s /opt/sonarscanner/sonar-scanner-4.0.0.1744-linux/bin/sonar-scanner /usr/local/bin/sonar-scanner
    displayName: 'install sonar-scanner'

  - script: |
      sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=kelkoo -Dsonar.login=6c199a8887e5909a63eb3d6ffcd70c1ca33d6757
    displayName: 'sonar-scanner'
