name: Backend CI

on:
  push:
    branches:
      - master
    paths:
    - '.github/workflows/backend.yml'
    - 'app/**'
    - 'conf/**'
    - 'local-conf/**'
    - 'project/**'
    - 'public/**'
    - 'test/**'
    - 'build.sbt'
    - 'scalastyle-config.xml'
    - 'sonar-project.properties'
    - 'version.sbt'
  pull_request:
    paths:
    - '.github/workflows/backend.yml'
    - 'app/**'
    - 'conf/**'
    - 'local-conf/**'
    - 'project/**'
    - 'public/**'
    - 'test/**'
    - 'build.sbt'
    - 'scalastyle-config.xml'
    - 'sonar-project.properties'
    - 'version.sbt'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      HAVE_SONAR_TOKEN: ${{ secrets.SONAR_TOKEN != '' }}

    steps:
    - uses: actions/checkout@v3

    - name: Sbt build cache
      uses: actions/cache@v3
      with:
        path: /home/runner/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties')}}

    - name: Yvy build cache
      uses: actions/cache@v3
      with:
        path: /home/runner/.ivy2
        key: ${{ runner.os }}-ivy-cache-${{ hashFiles('**/build.sbt')}}-${{ hashFiles('**/project/plugins.sbt')}}

    - name: Coursier build cache
      uses: actions/cache@v3
      with:
        path: /home/runner/.cache/coursier/v1
        key: ${{ runner.os }}-coursier-cache-${{ hashFiles('**/build.sbt')}}-${{ hashFiles('**/project/plugins.sbt')}}

    - name: Run tests
      run: sbt clean test scalastyle

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      if: ${{ env.HAVE_SONAR_TOKEN == 'true' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
