name: Frontend CI

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/frontend.yml'
      - 'frontend/**'
  pull_request:
    paths:
      - '.github/workflows/frontend.yml'
      - 'frontend/**'


jobs:
  build:

    runs-on: ubuntu-latest
    env:
      HAVE_SONAR_TOKEN: ${{ secrets.SONAR_TOKEN != '' }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: node modules cache
      uses: actions/cache@v3
      with:
        path: frontend/node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/frontend/package-lock.json')}}

    - name: npm cache
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: npm install
      run: |
        npm install -g @angular/cli
        npm install
        cd ./node_modules/protractor && npm i webdriver-manager@latest && cd ../..
        npm run pree2e
      working-directory: frontend

    - name: ng build
      run: ng build --no-progress --output-path ../public/dist
      working-directory: frontend

    - name: ng test && ng e2e
      run:  |
        export CI=true
        ng test --watch=false --progress=false --code-coverage
        # ng e2e
      working-directory: frontend

    - name: ng lint
      run: npx ng lint --format json --force --silent frontend > report.json
      working-directory: frontend

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      if: ${{ env.HAVE_SONAR_TOKEN == 'true' }}
      with:
        projectBaseDir: /github/workspace/frontend
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
